[[changing-similarities]]
=== Changing Similarities - Similarity 의 변경

유사성 알고리즘은 기본적으로 field 별로 설정할 수 있다.
((("relevance", "controlling", "changing similarities")))
((("similarity algorithms", "changing on a per-field basis")))
field mapping 에 선택한 알고리즘을 지정하면 된다.((("mapping (types)", "specifying similarity algorithm")))

[source,json]
------------------------------
PUT /my_index
{
  "mappings": {
    "doc": {
      "properties": {
        "title": {
          "type":       "string",
          "similarity": "BM25" <1>
        },
        "body": {
          "type":       "string",
          "similarity": "default" <2>
        }
      }
  }
}
------------------------------
<1> `title` field는 BM25 를 사용한다.
<2> `body` 는 기본 알고리즘을 사용한다. (<<practical-scoring-function>> 참고).

현재, 기존의 field 에 대해 `similarity` mapping 을 변경하는 것은 불가능하다.
이를 위해서는 데이터를 다시 색인 해야 한다.

==== Configuring BM25 - BM25 의 설정

similarity 의 설정은 analyzer 의 설정과 매우 유사하다.
((("similarity algorithms", "configuring custom similarities")))((("BM25", "configuring")))
사용자 정의 similarity 는 index 를 생성할 때 지정할 수 있다.

[source,json]
------------------------------
PUT /my_index
{
  "settings": {
    "similarity": {
      "my_bm25": { <1>
        "type": "BM25",
        "b":    0 <2>
      }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "title": {
          "type":       "string",
          "similarity": "my_bm25" <3>
        },
        "body": {
          "type":       "string",
          "similarity": "BM25" <4>
        }
      }
    }
  }
}
------------------------------
<1> 내장된 `BM25` similarity 를 기반으로, `my_bm25` 라 불리는 사용자 정의 similarity 를 생성한다.
<2> field-length normalization 을 비활성화. <<bm25-tunability>> 참고
<3> `title` field는 사용자 정의 similarity `my_bm25` 를 사용한다.
<4> `body` field는 내장된 similarity `BM25` 를 사용한다.

TIP: index 를 닫고, index 설정을 업데이트하고, index 를 다시 open 하여,
     사용자 정의 similarity 를 업데이트할 수 있다.
     이를 이용해 document 를 다시 색인 하지 않고, 다른 설정을 실험할 수 있다.
